class PatientForm
  include ActiveModel::Model

  attr_accessor(
    :first_name,
    :last_name,
    :cellphone_number,
    :address,
    :email,
    :relative_cellphone_number,
    :general_practitioner,
    :covid_general_practitioner,
    :gender,
    :birthdate,
    :is_healthcare_professional,
    :pregnant,
    :pregnant_since_in_weeks,
    :home_caregivers,
    :home_caregivers_type,
    :covid_initial_symptom,
    :covid_initial_symptoms_diagnosed_on,
    :covid_initial_symptoms_started_on,
    :covid_treatment_started_on,
    :interstitial_alveolus_infiltrates,
    :notable_long_term_treatments,
    :sars_cov_2_treatment,
    :sars_cov_2_treatment_name,
    :home_follow_up_elligible,
    :comorbidity_chronic_cardiac_disease,
    :comorbidity_chronic_pulmonary_disease,
    :comorbidity_asthma,
    :comorbidity_chronic_kidney_disease,
    :comorbidity_liver_disease,
    :comorbidity_mild_liver_disease,
    :comorbidity_chronic_neurological_disorder,
    :comorbidity_malignant_neoplasia,
    :comorbidity_chronic_hemathological_disease,
    :comorbidity_hiv,
    :comorbidity_obesity,
    :comorbidity_diabetes_with_complications,
    :comorbidity_diabetes,
    :comorbidity_rheumatologic_disease,
    :comorbidity_dementia,
    :comorbidity_malnutrition,
    :comorbidity_smoking,
    :comorbidity_other,
    :comorbidity_other_comment,
    :command_center_id
  )

  validates_presence_of :first_name, :last_name, :cellphone_number, :gender, :birthdate, :pregnant, :pregnant_since_in_weeks, :comorbidity_chronic_cardiac_disease,
    :comorbidity_chronic_pulmonary_disease, :comorbidity_asthma, :comorbidity_chronic_kidney_disease, :comorbidity_liver_disease, :comorbidity_mild_liver_disease, :comorbidity_chronic_neurological_disorder, :comorbidity_malignant_neoplasia, :comorbidity_chronic_hemathological_disease, :comorbidity_hiv, :comorbidity_obesity, :comorbidity_diabetes_with_complications, :comorbidity_diabetes, :comorbidity_rheumatologic_disease, :comorbidity_dementia, :comorbidity_malnutrition, :comorbidity_smoking, :covid_initial_symptoms_started_on, :sars_cov_2_treatment, :home_caregivers

  private

    def patient_attributes
      {
        first_name: first_name,
        last_name: last_name,
        cellphone_number: cellphone_number,
        address: address,
        email: email,
        relative_cellphone_number: relative_cellphone_number,
        general_practitioner: general_practitioner,
        covid_general_practitioner: covid_general_practitioner,
        gender: gender,
        birthdate: birthdate,
        is_healthcare_professional: is_healthcare_professional,
        pregnant: pregnant,
        pregnant_since_in_weeks: pregnant_since_in_weeks,
        home_caregivers: home_caregivers,
        home_caregivers_type: home_caregivers_type,
        covid_initial_symptom: covid_initial_symptom,
        covid_initial_symptoms_diagnosed_on: covid_initial_symptoms_diagnosed_on,
        covid_initial_symptoms_started_on: covid_initial_symptoms_started_on,
        covid_treatment_started_on: covid_treatment_started_on,
        interstitial_alveolus_infiltrates: interstitial_alveolus_infiltrates,
        notable_long_term_treatments: notable_long_term_treatments,
        sars_cov_2_treatment: sars_cov_2_treatment,
        sars_cov_2_treatment_name: sars_cov_2_treatment_name,
        home_follow_up_elligible: home_follow_up_elligible,
        comorbidity_chronic_cardiac_disease: comorbidity_chronic_cardiac_disease,
        comorbidity_chronic_pulmonary_disease: comorbidity_chronic_pulmonary_disease,
        comorbidity_asthma: comorbidity_asthma,
        comorbidity_chronic_kidney_disease: comorbidity_chronic_kidney_disease,
        comorbidity_liver_disease: comorbidity_liver_disease,
        comorbidity_mild_liver_disease: comorbidity_mild_liver_disease,
        comorbidity_chronic_neurological_disorder: comorbidity_chronic_neurological_disorder,
        comorbidity_malignant_neoplasia: comorbidity_malignant_neoplasia,
        comorbidity_chronic_hemathological_disease: comorbidity_chronic_hemathological_disease,
        comorbidity_hiv: comorbidity_hiv,
        comorbidity_obesity: comorbidity_obesity,
        comorbidity_diabetes_with_complications: comorbidity_diabetes_with_complications,
        comorbidity_diabetes: comorbidity_diabetes,
        comorbidity_rheumatologic_disease: comorbidity_rheumatologic_disease,
        comorbidity_dementia: comorbidity_dementia,
        comorbidity_malnutrition: comorbidity_malnutrition,
        comorbidity_smoking: comorbidity_smoking,
        comorbidity_other: comorbidity_other,
        comorbidity_other_comment: comorbidity_other_comment,
        command_center_id: command_center_id
      }
    end

end